title: GPGPU with GLES
author: "Jakub Duchniewicz"
description: > # this means to ignore newlines until "show_excerpts:"
  Website for Google Summer of Code 2021 BeagleBone project GPGPU with GLES. Weekly updates and technical posts.

show_excerpts: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"


github_username: JDuchniewicz
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: minima

header_pages:
  - _pages/frontpage.md

include:
  - _pages
  
exclude: 
  - .gitignore
  - LICENSE
  - README.md
    
plugins:
 - jekyll-feed
 - jekyll-seo-tag
